"""Build the inline London mini-map shown on the loading screen.

The loading screen has to draw something recognisable before any of the real
data has arrived, which rules out fetching geometry for it. So this script
bakes a heavily simplified ward map, plus one IMD decile per ward, into a
single compact string that is spliced straight into index.html.

The output is deliberately small. At the size the loader draws it (about
360px across) the full ONS ward geometry carries far more precision than the
screen can show, so it is simplified with Ramer-Douglas-Peucker, quantised to
a 1000 unit box, delta encoded and packed into a base64 style varint. That
turns roughly 600 KB of ward outlines into about 20 KB of string.

Run after any change to the ward boundaries or the IMD data:

    py scripts/build_loader_map.py

It rewrites the block between the LOADER MAP markers in index.html and makes
no other change to the file.
"""

from __future__ import annotations

import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WARDS_JS = ROOT / "data" / "map" / "wards.js"
IMD_JS = ROOT / "data" / "map" / "lsoa_imd.js"
INDEX = ROOT / "index.html"

BEGIN = "/* ── LOADER MAP: generated by scripts/build_loader_map.py ── */"
END = "/* ── end LOADER MAP ── */"

# URL safe base64. No character in here needs escaping inside a single quoted
# JS string sitting in an HTML document, which is where this ends up.
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"

# The box the geometry is quantised into. 1000 is comfortably more precision
# than a 360px render needs, which leaves room for the loader to be drawn
# larger on a big screen without going visibly polygonal.
BOX = 1000

# In degrees. The loader draws at about 340px for a span of roughly 60km, so
# one pixel is about 175 metres and anything finer than that is precision the
# screen throws away. This is a little under a pixel: past it the Thames starts
# losing its bends and the outer borough edges go visibly straight.
TOLERANCE = 0.0011


def read_js_const(path: Path, name: str) -> dict:
    """Pull a `var NAME = {...};` blob out of one of the map data files."""
    text = path.read_text(encoding="utf-8")
    marker = f"var {name} = "
    start = text.index(marker) + len(marker)
    end = text.rindex("}") + 1
    return json.loads(text[start:end])


def perpendicular_distance(pt, start, end) -> float:
    if start == end:
        return math.hypot(pt[0] - start[0], pt[1] - start[1])
    dx, dy = end[0] - start[0], end[1] - start[1]
    t = ((pt[0] - start[0]) * dx + (pt[1] - start[1]) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    px, py = start[0] + t * dx, start[1] + t * dy
    return math.hypot(pt[0] - px, pt[1] - py)


def rdp(points: list, tolerance: float) -> list:
    """Ramer-Douglas-Peucker, iterative so a long ring cannot blow the stack."""
    if len(points) < 3:
        return points
    keep = [False] * len(points)
    keep[0] = keep[-1] = True
    stack = [(0, len(points) - 1)]
    while stack:
        first, last = stack.pop()
        if last <= first + 1:
            continue
        worst, worst_i = 0.0, first
        for i in range(first + 1, last):
            d = perpendicular_distance(points[i], points[first], points[last])
            if d > worst:
                worst, worst_i = d, i
        if worst > tolerance:
            keep[worst_i] = True
            stack.append((first, worst_i))
            stack.append((worst_i, last))
    return [p for p, k in zip(points, keep) if k]


def largest_ring(geometry: dict) -> list:
    """The outer ring of the biggest part. Islands and holes are not legible
    at this size and only cost bytes."""
    if geometry["type"] == "Polygon":
        rings = [geometry["coordinates"][0]]
    elif geometry["type"] == "MultiPolygon":
        rings = [poly[0] for poly in geometry["coordinates"]]
    else:
        return []
    return max(rings, key=len) if rings else []


def encode_varints(values) -> str:
    """Zigzag varint, five bits per character, high bit continues."""
    out = []
    for v in values:
        z = (v << 1) ^ (v >> 31) if v < 0 else (v << 1)
        while True:
            chunk = z & 31
            z >>= 5
            out.append(ALPHABET[chunk | 32] if z else ALPHABET[chunk])
            if not z:
                break
    return "".join(out)


def main() -> int:
    if not WARDS_JS.exists() or not IMD_JS.exists():
        print(f"missing input: {WARDS_JS} or {IMD_JS}", file=sys.stderr)
        return 1

    print("reading ward boundaries...")
    wards = read_js_const(WARDS_JS, "GJ")

    print("reading IMD and averaging to ward...")
    imd = read_js_const(IMD_JS, "LSOA_IMD")
    totals: dict[str, list[int]] = {}
    for feat in imd["features"]:
        props = feat.get("properties") or {}
        code, decile = props.get("ward_code"), props.get("imd_decile")
        if code and isinstance(decile, (int, float)):
            totals.setdefault(code, []).append(int(decile))
    ward_decile = {
        code: max(1, min(10, round(sum(v) / len(v)))) for code, v in totals.items()
    }
    print(f"  {len(ward_decile)} of {len(wards['features'])} wards have an IMD mean")

    # Project. Equirectangular with a cosine correction at London's latitude is
    # accurate enough over 60km and needs no projection library.
    feats = []
    for feat in wards["features"]:
        ring = largest_ring(feat.get("geometry") or {})
        if len(ring) < 4:
            continue
        props = feat.get("properties") or {}
        feats.append((props.get("WD24CD", ""), ring))

    if not feats:
        print("no ward geometry found", file=sys.stderr)
        return 1

    lats = [pt[1] for _, ring in feats for pt in ring]
    lons = [pt[0] for _, ring in feats for pt in ring]
    lat0 = (min(lats) + max(lats)) / 2
    k = math.cos(math.radians(lat0))

    xs = [lon * k for lon in lons]
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(lats), max(lats)
    span = max(max_x - min_x, max_y - min_y)
    scale = BOX / span
    width = round((max_x - min_x) * scale)
    height = round((max_y - min_y) * scale)

    def project(pt):
        x = (pt[0] * k - min_x) * scale
        # SVG y grows downward, latitude grows upward.
        y = (max_y - pt[1]) * scale
        return round(x), round(y)

    print(f"simplifying {len(feats)} wards at tolerance {TOLERANCE}...")
    packed, deciles, kept, raw_points, simple_points = [], [], 0, 0, 0
    for code, ring in feats:
        raw_points += len(ring)
        simplified = rdp(ring, TOLERANCE)
        pts, last = [], None
        for pt in simplified:
            xy = project(pt)
            if xy != last:
                pts.append(xy)
                last = xy
        # A ward that collapses to a sliver at this scale is not worth drawing.
        if len(pts) < 3:
            continue
        simple_points += len(pts)
        kept += 1

        values = [len(pts), pts[0][0], pts[0][1]]
        for i in range(1, len(pts)):
            values.append(pts[i][0] - pts[i - 1][0])
            values.append(pts[i][1] - pts[i - 1][1])
        packed.append(encode_varints(values))
        deciles.append(ALPHABET[ward_decile.get(code, 0)])

    blob = "".join(packed)
    decile_str = "".join(deciles)
    print(
        f"  {kept} wards, {raw_points} points in, {simple_points} out "
        f"({simple_points / raw_points:.1%})"
    )
    print(f"  encoded {len(blob) / 1024:.1f} KB")

    block = (
        f"{BEGIN}\n"
        "/* A simplified ward map of London with one IMD decile per ward, so the\n"
        "   loading screen can draw something true before any data has loaded.\n"
        "   Delta encoded varints in a base64 alphabet: see the decoder in\n"
        "   _paintLoaderMap, and scripts/build_loader_map.py for how it is made.\n"
        "   Do not hand edit. */\n"
        f"var LOADER_MAP = {{w:{width},h:{height},n:{kept},"
        f"d:'{decile_str}',p:'{blob}'}};\n"
        f"{END}"
    )

    html = INDEX.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(BEGIN) + ".*?" + re.escape(END), re.DOTALL
    )
    if not pattern.search(html):
        print(
            "LOADER MAP markers not found in index.html. Add them first:\n"
            f"  {BEGIN}\n  {END}",
            file=sys.stderr,
        )
        return 1

    INDEX.write_text(pattern.sub(lambda _: block, html, count=1), encoding="utf-8")
    print(f"spliced into {INDEX.name} ({width}x{height} viewBox)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
