"""Self-host the web fonts.

The site used to link fonts.googleapis.com directly. That is a third-party
request on a public sector site, and the audience for this map sits behind
NHS and local authority networks that block Google more often than most: when
the request fails the typography silently falls back and the layout shifts.

This downloads the woff2 files and writes a stylesheet that points at them.
Only the latin and latin-ext subsets are kept. Every other subset Google
offers (cyrillic, greek, vietnamese) is dead weight here, and because each
face carries a unicode-range the browser still only downloads latin-ext when
a name on the page actually needs it.

Run when the font families or weights in index.html change:

    py scripts/build_fonts.py
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_CSS = ROOT / "vendor" / "fonts.css"
OUT_DIR = ROOT / "vendor" / "fonts"

# Must match the families and weights the stylesheet in index.html asks for.
GOOGLE_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=Inter:wght@400;500;600;700"
    "&family=Inter+Tight:wght@500;600;700"
    "&family=JetBrains+Mono:wght@400;500"
    "&display=swap"
)

# Google serves woff2 only to browsers it recognises. Without this it returns
# the truetype stylesheet, which is several times the size.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

KEEP_SUBSETS = ("latin", "latin-ext")


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def main() -> int:
    print(f"fetching stylesheet from {GOOGLE_CSS.split('?')[0]} ...")
    try:
        css = get(GOOGLE_CSS).decode("utf-8")
    except Exception as exc:
        print(f"could not reach Google Fonts: {exc}", file=sys.stderr)
        return 1

    blocks = re.findall(r"/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css)
    keep = [(sub, b) for sub, b in blocks if sub in KEEP_SUBSETS]
    if not keep:
        print("no matching @font-face blocks found", file=sys.stderr)
        return 1
    print(f"  {len(blocks)} faces offered, keeping {len(keep)} in {KEEP_SUBSETS}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rewritten, total = [], 0
    for subset, block in keep:
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)

        name = f"{family.replace(' ', '')}-{weight}-{subset}.woff2"
        data = get(url)
        (OUT_DIR / name).write_bytes(data)
        total += len(data)
        rewritten.append(f"/* {subset} */\n" + block.replace(url, f"fonts/{name}"))
        print(f"  {name:38s} {len(data) / 1024:6.1f} KB")

    header = (
        "/* Self-hosted web fonts. Generated by scripts/build_fonts.py.\n"
        "   Do not hand edit: rerun the script instead.\n"
        "\n"
        "   Served from this repo rather than fonts.googleapis.com so the site\n"
        "   makes no third-party request and keeps its typography on a network\n"
        "   that blocks Google. latin and latin-ext only; the unicode-range on\n"
        "   each face means latin-ext is fetched only when a name needs it. */\n\n"
    )
    OUT_CSS.write_text(header + "\n\n".join(rewritten) + "\n", encoding="utf-8")
    print(f"wrote {OUT_CSS.relative_to(ROOT)} and {len(keep)} files, "
          f"{total / 1024:.0f} KB total")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
