#!/usr/bin/env python3
"""Every London postcode, with the figures held for the area it sits in.

A one-off extract, not part of the map. Nothing here is served by the site.

    python scripts/build_postcode_table.py [-o OUT.csv] [--terminated] [--slim]

## What it joins, and why only one column comes from ONSPD

ONSPD is used for exactly one thing: postcode -> lsoa21cd. Everything else is
taken from this repo's own files, which already agree with each other:

    ONSPD            pcds, lsoa21cd            (and doterm, lat, long)
    lsoa_imd.js      LSOA name, ward, ward code, borough
    lsoa_data.json   60 LSOA figures
    ward_data.json   105 ward figures, and the borough name

The ward comes from ONSPD too, and that was worth checking rather than
assuming. ONSPD Feb 2026 carries wd25cd where these wards are WD24, so the
first build derived the ward from the LSOA instead, to avoid joining across two
vintages. Measured against all 180,983 live London postcodes, wd25cd matched a
known ward code 180,982 times: there is no vintage gap to avoid.

There is a real cost the other way. An LSOA is assigned to exactly one ward by
best fit, but LSOAs cross ward boundaries, so deriving the ward from the LSOA
put 13,869 postcodes, 7.66% of London, in a ward they are not in. The City of
London was worst: 25 wards share a handful of LSOAs, so 20 of them came out
with no postcodes at all while their postcodes were labelled with a neighbour.
ONSPD knows which ward each postcode is actually in, so it is used.

One consequence is unavoidable and is worth stating. ward_imd_*_mean was
aggregated by this project over the LSOAs best-fitted to each ward, so for a
postcode whose LSOA best-fits elsewhere, the ward figure was computed from a
slightly different set of LSOAs than the one it sits in. That is how the ward
aggregates are built and cannot be fixed from here.

Vintage matters on the LSOA too: lsoa21cd, never lsoa11cd. London had 4,835
LSOAs in 2011 and has 4,994 now, and joining on the wrong one silently
mismatches every area that changed.

"London" here means "the postcode's LSOA is one of the 4,994 this project
holds". No separate region or local-authority filter, so the output cannot
disagree with the map about what London is.

## Two things about the columns

IMD is published at LSOA and nowhere else. The lsoa_imd_* columns are that
published figure. The ward_imd_* columns are population-weighted aggregates
computed by this project from the LSOAs in each ward, which is why they are
named _mean. ward_imd_decile_mean is an average of deciles and is not itself a
decile: 3.0 means the typical LSOA there sits in the third decile, not that the
ward is in the most deprived tenth.

18 of the 105 ward figures are published per borough and repeated across every
ward in it. ft_life_expectancy_male, for instance, holds one value across all
24 Barnet wards. Those columns are suffixed _borough so the name carries the
warning: the figure describes a borough of several hundred thousand people, not
the postcode it appears against.

## And the thing this file cannot do

Every figure here describes the LSOA, ward or borough the postcode falls in. It
does not describe the postcode, the addresses in it, or anyone living there. An
LSOA holds about 1,500 people; a postcode holds about 15 addresses. Assigning
one to the other is an ecological assignment, and reading it back as a fact
about a household reverses it. That sentence is written into the file header.
"""

import argparse
import csv
import io
import json
import pathlib
import re
import sys
import zipfile

REPO = pathlib.Path(__file__).resolve().parent.parent
ONSPD_ZIP = REPO / ".cache" / "onspd" / "ONSPD_FEB_2026_UK.zip"
ONSPD_MEMBER = "Data/ONSPD_FEB_2026_UK.csv"

# The same rule index.html uses in isBoroughLevelKey: a named ft_ series is
# published per local authority, a numbered one is a ward-level Local Health
# indicator.
def is_borough_level(key):
    return key.startswith("ft_") and not re.match(r"^ft_\d+$", key)


HEADER_NOTE = [
    "# Every London postcode, with the figures held for the area it falls in.",
    "# Generated by scripts/build_postcode_table.py from ONSPD FEB 2026 and this",
    "# project's own LSOA and ward data. Contains OS data (c) Crown copyright and",
    "# database right; Contains Royal Mail data (c) Royal Mail copyright and",
    "# database right; Source: Office for National Statistics licensed under the",
    "# Open Government Licence v3.0.",
    "#",
    "# READ THIS BEFORE USING A ROW.",
    "# Every figure describes the LSOA, ward or borough the postcode falls in. None",
    "# of them describes the postcode, the addresses in it, or anyone living there.",
    "# An LSOA holds about 1,500 people and a postcode about 15 addresses, so these",
    "# figures are repeated across roughly 35 postcodes each. Reading one back as a",
    "# fact about a household or a person reverses what it measures.",
    "#",
    "# lsoa_imd_* is the published IMD 2025 figure for that LSOA.",
    "# ward_imd_*_mean is a population-weighted aggregate of the LSOAs in the ward,",
    "#   computed here. It is not a published figure. A decile mean is not a decile.",
    "# Columns ending _borough are published per borough and repeated across every",
    "#   ward in it, so they say nothing about this postcode's ward or LSOA.",
    "# The ward is the one ONSPD puts the postcode in. The ward figures were",
    "#   aggregated over the LSOAs best-fitted to that ward, which for some",
    "#   postcodes is a slightly different set from the LSOA they sit in.",
]


def load_geography():
    """LSOA code -> name, ward, ward code, borough. From the map's own file."""
    src = (REPO / "data" / "map" / "lsoa_imd.js").read_text(encoding="utf-8", errors="replace")
    gj = json.loads(src[src.index("{"): src.rindex("}") + 1])
    geo = {}
    for f in gj["features"]:
        p = f.get("properties") or {}
        if p.get("code"):
            geo[p["code"]] = p
    return geo


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out", default=str(REPO / "postcode_lsoa_metrics.csv"))
    ap.add_argument("--terminated", action="store_true",
                    help="include postcodes that have been retired (doterm set)")
    ap.add_argument("--slim", action="store_true",
                    help="geography and IMD only, without the other 150-odd figures")
    args = ap.parse_args()

    if not ONSPD_ZIP.exists():
        sys.exit(f"missing {ONSPD_ZIP}")

    geo = load_geography()
    lsoa = json.loads((REPO / "lsoa_data.json").read_text(encoding="utf-8"))
    wards = json.loads((REPO / "ward_data.json").read_text(encoding="utf-8"))["wards"]
    print(f"geography {len(geo):,} LSOAs | figures {len(lsoa):,} LSOAs | {len(wards):,} wards")

    # Stable column order, and prefixed: both sides publish imd_score,
    # ptal_score and a census_ block, so unprefixed they would collide and the
    # ward value would quietly overwrite the LSOA one.
    lsoa_keys = sorted({k for v in lsoa.values() for k in (v.get("indicators") or v)})
    ward_keys = sorted({k for v in wards.values() for k in (v.get("indicators") or {})})
    IMD_L = ["imd_score", "imd_decile", "imd_rank"]
    IMD_W = ["imd_score", "imd_decile_mean"]
    lsoa_rest = [k for k in lsoa_keys if k not in IMD_L]
    ward_rest = [k for k in ward_keys if k not in IMD_W]

    head = ["postcode", "lsoa21cd", "lsoa_name",
            "lsoa_imd_score", "lsoa_imd_decile", "lsoa_imd_rank",
            "ward_code", "ward_name", "ward_imd_score_mean", "ward_imd_decile_mean",
            "lad_code", "lad_name", "lat", "long"]
    if args.terminated:
        head.append("terminated")
    if not args.slim:
        head += ["lsoa_" + k for k in lsoa_rest]
        head += [("ward_" + k + "_borough") if is_borough_level(k) else ("ward_" + k)
                 for k in ward_rest]

    n_bor = sum(1 for k in ward_rest if is_borough_level(k))
    print(f"columns {len(head)} | {n_bor} ward columns are borough figures, suffixed _borough")

    out = pathlib.Path(args.out)
    kept = skipped_geo = skipped_term = 0
    with out.open("w", encoding="utf-8", newline="") as fh:
        for line in HEADER_NOTE:
            fh.write(line + "\n")
        w = csv.writer(fh)
        w.writerow(head)

        z = zipfile.ZipFile(ONSPD_ZIP)
        with z.open(ONSPD_MEMBER) as raw:
            r = csv.reader(io.TextIOWrapper(raw, encoding="utf-8-sig", newline=""))
            cols = next(r)
            ix = {c: i for i, c in enumerate(cols)}
            for need in ("pcds", "lsoa21cd", "wd25cd", "doterm", "lat", "long"):
                if need not in ix:
                    sys.exit(f"ONSPD is missing the {need} column")
            i_pc, i_ls, i_wd = ix["pcds"], ix["lsoa21cd"], ix["wd25cd"]
            i_dt, i_la, i_lo = ix["doterm"], ix["lat"], ix["long"]

            for row in r:
                code = row[i_ls]
                g = geo.get(code)
                if not g:
                    skipped_geo += 1
                    continue                      # not one of the 4,994: not London
                term = (row[i_dt] or "").strip()
                if term and not args.terminated:
                    skipped_term += 1
                    continue

                li = (lsoa.get(code) or {})
                li = li.get("indicators", li)
                # ONSPD knows the postcode's actual ward. The LSOA's best-fit
                # ward is the fallback for the one postcode whose code is not in
                # the 704, so a row never comes out with no ward at all.
                wc = row[i_wd]
                if wc not in wards:
                    wc = g.get("ward_code") or ""
                wr = wards.get(wc) or {}
                wi = wr.get("indicators") or {}

                rec = [row[i_pc], code, g.get("name", ""),
                       li.get("imd_score", ""), li.get("imd_decile", ""), li.get("imd_rank", ""),
                       wc, wr.get("name", g.get("ward", "")),
                       wi.get("imd_score", ""), wi.get("imd_decile_mean", ""),
                       wr.get("lad_code", ""), wr.get("lad", g.get("borough", "")),
                       row[i_la], row[i_lo]]
                if args.terminated:
                    rec.append(term)
                if not args.slim:
                    rec += [li.get(k, "") for k in lsoa_rest]
                    rec += [wi.get(k, "") for k in ward_rest]
                w.writerow(rec)
                kept += 1
                if kept % 50000 == 0:
                    print(f"  {kept:,} postcodes written")

    mb = out.stat().st_size / 1e6
    print()
    print(f"wrote {kept:,} London postcodes to {out}  ({mb:,.1f} MB)")
    print(f"  skipped {skipped_geo:,} outside London")
    if not args.terminated:
        print(f"  skipped {skipped_term:,} terminated (pass --terminated to keep them)")


if __name__ == "__main__":
    main()
