"""Build the whole-of-England view (?r=england) from the published regions.

England is shown at local authority level only: every council in England on
one map, shaded by the indicators published per local authority. There is no
new data to fetch. Each region build already writes its councils' outlines
(map/boroughs.js) and their Fingertips figures (borough_data.json), and London
has the same two files at the repo root, so this stitches them together.

It runs in the site deploy (jekyll-gh-pages.yml), after the region packs are
unpacked, so England always matches the regions published alongside it. A
region that is not published yet is simply absent, and is listed in the
output's meta/manifest.json.

    py scripts/build_england.py

Writes data/regions/england/:
  map/boroughs.js      every council, simplified, with its region's slug
  borough_data.json    every council's figures, keyed by LAD code
  map/indicators.js    5th to 95th percentile ranges across all councils
  map/loader.js        the loading screen's council map, shaded by mean IMD
  map/wards.js, gp_practices.js, hospitals.js, custom.js
                       empty: England has no ward level, and the page needs
                       the globals to exist
  ward_data.json       empty, for the same reason
  meta/manifest.json   London's manifest, with the regions included
"""

from __future__ import annotations

import json
import math
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from build_loader_map import ALPHABET, encode_varints, rdp  # noqa: E402

OUT = ROOT / "data" / "regions" / "england"

# Degrees. About 150 m: at the zoom England fits on a screen a council edge
# loses nothing visible, and 296 councils come down from tens of MB to a few.
TOLERANCE = 0.0015


def read_js(path: Path, name: str):
    text = path.read_text(encoding="utf-8")
    marker = f"var {name} = "
    start = text.index(marker) + len(marker)
    end = max(text.rfind("}"), text.rfind("]")) + 1
    return json.loads(text[start:end])


def write_js(path: Path, name: str, value, note: str) -> None:
    path.write_text(
        f"// {note}\n// Generated by scripts/build_england.py. Do not hand edit.\n"
        f"var {name} = {json.dumps(value, separators=(',', ':'), ensure_ascii=False)};\n",
        encoding="utf-8")


def simplify(geom: dict) -> dict | None:
    def ring(r):
        pts = rdp([[round(x, 4), round(y, 4)] for x, y in r], TOLERANCE)
        return pts if len(pts) >= 4 else None

    if geom["type"] == "Polygon":
        polys = [geom["coordinates"]]
    elif geom["type"] == "MultiPolygon":
        polys = geom["coordinates"]
    else:
        return None
    out = []
    for poly in polys:
        outer = ring(poly[0])
        if outer:
            out.append([outer] + [h for h in (ring(r) for r in poly[1:]) if h])
    if not out:
        return None
    return {"type": "MultiPolygon", "coordinates": out}


def sources() -> list[tuple[str, Path]]:
    """(region slug, directory holding borough_data.json and map/)."""
    found = [("london", ROOT)]
    for scope in sorted((ROOT / "scopes").glob("*.json")):
        slug = scope.stem
        if slug in ("london", "england"):
            continue
        d = ROOT / "data" / "regions" / slug
        if (d / "map" / "boroughs.js").exists() and (d / "borough_data.json").exists():
            found.append((slug, d))
    return found


def mean_imd(src: Path) -> dict:
    """Council name -> mean LSOA IMD decile, for the loading map."""
    path = src / ("data/map/lsoa_imd.js" if src == ROOT else "map/lsoa_imd.js")
    if not path.exists():
        return {}
    acc: dict = {}
    for f in read_js(path, "LSOA_IMD").get("features", []):
        p = f.get("properties") or {}
        if p.get("borough") and isinstance(p.get("imd_decile"), (int, float)):
            acc.setdefault(p["borough"], []).append(p["imd_decile"])
    return {k: max(1, min(10, round(sum(v) / len(v)))) for k, v in acc.items()}


def loader_map(features: list, deciles: dict) -> dict:
    """The same encoding as build_loader_map.py, drawn from council outlines."""
    rings = []
    for f in features:
        parts = f["geometry"]["coordinates"]
        rings.append((f["properties"]["name"], max((p[0] for p in parts), key=len)))
    lats = [pt[1] for _, r in rings for pt in r]
    lons = [pt[0] for _, r in rings for pt in r]
    k = math.cos(math.radians((min(lats) + max(lats)) / 2))
    min_x, max_x = min(lons) * k, max(lons) * k
    min_y, max_y = min(lats), max(lats)
    scale = 1000 / max(max_x - min_x, max_y - min_y)
    packed, dec = [], []
    for name, ring in rings:
        pts, last = [], None
        for pt in rdp(ring, 0.01):
            xy = (round((pt[0] * k - min_x) * scale), round((max_y - pt[1]) * scale))
            if xy != last:
                pts.append(xy)
                last = xy
        if len(pts) < 3:
            continue
        vals = [len(pts), pts[0][0], pts[0][1]]
        for i in range(1, len(pts)):
            vals += [pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]]
        packed.append(encode_varints(vals))
        dec.append(ALPHABET[deciles.get(name, 0)])
    return {"w": round((max_x - min_x) * scale), "h": round((max_y - min_y) * scale),
            "n": len(packed), "d": "".join(dec), "p": "".join(packed)}


def main() -> int:
    srcs = sources()
    features, data, deciles, seen = [], {}, {}, set()
    for slug, src in srcs:
        gj_path = src / ("data/map/boroughs.js" if slug == "london" else "map/boroughs.js")
        gj = read_js(gj_path, "BOROUGH_GJ")
        bd = json.loads((src / "borough_data.json").read_text(encoding="utf-8"))
        deciles.update(mean_imd(src))
        n = 0
        for f in gj.get("features", []):
            p = f.get("properties") or {}
            code = next((v for k, v in p.items() if k.startswith("LAD") and k.endswith("CD")), None)
            if not code or code in seen:
                continue
            geom = simplify(f["geometry"])
            if not geom:
                continue
            seen.add(code)
            features.append({"type": "Feature",
                             "properties": {"name": p.get("name"), "LAD25CD": code, "region": slug},
                             "geometry": geom})
            if code in bd:
                data[code] = bd[code]
            n += 1
        print(f"  {slug:26s} {n:>3} councils")

    expected = {c for s in (ROOT / "scopes").glob("*.json") if s.stem != "england"
                for _, c in json.loads(s.read_text(encoding="utf-8"))["lads"]}
    missing_regions = sorted(s.stem for s in (ROOT / "scopes").glob("*.json")
                             if s.stem not in {x for x, _ in srcs} | {"england"})
    print(f"{len(features)} of {len(expected)} councils; "
          f"regions not published yet: {missing_regions or 'none'}")

    # Ranges across every council, the same shape indicators.js has for a region.
    london = read_js(ROOT / "data/map/indicators.js", "PH_IND_STATS").get("stats", {})
    keys = sorted({k for rec in data.values() for k in (rec.get("indicators") or rec)})
    stats = {}
    for k in keys:
        vals = sorted(float(v) for rec in data.values()
                      for v in [(rec.get("indicators") or rec).get(k)]
                      if isinstance(v, (int, float)))
        if len(vals) < 2:
            continue
        lv = {"n": len(vals), "d": len(set(vals)),
              "p5": vals[int(len(vals) * 0.05)], "p95": vals[math.ceil(len(vals) * 0.95) - 1]}
        stats[k] = {"lv": {"borough": lv}}
        if k in london and london[k].get("yr"):
            stats[k]["yr"] = london[k]["yr"]

    (OUT / "map").mkdir(parents=True, exist_ok=True)
    (OUT / "meta").mkdir(parents=True, exist_ok=True)
    write_js(OUT / "map/boroughs.js", "BOROUGH_GJ",
             {"type": "FeatureCollection", "features": features},
             "Every local authority in England, from the published regions.")
    write_js(OUT / "map/indicators.js", "PH_IND_STATS",
             {"generated": datetime.now(timezone.utc).isoformat(), "stats": stats},
             "Ranges across every council in England.")
    write_js(OUT / "map/wards.js", "GJ", {"type": "FeatureCollection", "features": []},
             "England has no ward level; see a region for wards.")
    write_js(OUT / "map/gp_practices.js", "GPS", [], "No point layers at England level.")
    write_js(OUT / "map/hospitals.js", "HOSP", [], "No point layers at England level.")
    write_js(OUT / "map/custom.js", "PH_CUSTOM", [], "No custom indicators at England level.")
    (OUT / "map/loader.js").write_text(
        "// The loading screen's council map for England, made by scripts/build_england.py.\n"
        f"var REGION_LOADER_MAP = {json.dumps(loader_map(features, deciles), separators=(',', ':'))};\n",
        encoding="utf-8")
    (OUT / "borough_data.json").write_text(json.dumps(data, separators=(",", ":")), encoding="utf-8")
    (OUT / "ward_data.json").write_text('{"wards":{},"metadata":{}}', encoding="utf-8")
    manifest = json.loads((ROOT / "data/meta/manifest.json").read_text(encoding="utf-8"))
    manifest["england"] = {"regions": [s for s, _ in srcs], "not_yet_published": missing_regions,
                           "councils": len(features)}
    (OUT / "meta/manifest.json").write_text(json.dumps(manifest, indent=1), encoding="utf-8")
    kb = (OUT / "map/boroughs.js").stat().st_size / 1024
    print(f"wrote {OUT.relative_to(ROOT)} (council outlines {kb:,.0f} kB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
