"""Build the whole-of-England view (?r=england) from the published regions.

England is a region like any other: wards, LSOAs, MSOAs, councils, ICBs,
GPs, hospitals, pharmacies and dentists, with every indicator, for the whole
country on one map. There is nothing new to fetch. Each region build has
already written its files, and London has the same files at the repo root,
so this merges them into data/regions/england/.

It runs in the site deploy (jekyll-gh-pages.yml), after the region packs are
unpacked, so England always matches the regions published alongside it. A
region not published yet is simply absent, and is listed in the output's
meta/manifest.json.

    py scripts/build_england.py

Merging is mostly concatenation, with four things done on the way:

  * Ward names that occur in more than one council are given the council in
    brackets ("Abbey (Barking and Dagenham)"), as London already does for its
    own duplicates. The page indexes wards by that display name.
  * Geometry is simplified a little more than in a region, so the whole
    country stays loadable. A ward edge moves by at most about 25 m.
  * Indicator ranges (map/indicators.js) are recomputed across England, and an
    indicator only one region carries (London's transport measures) is left
    out rather than shown as a mostly empty map.
  * Integrated Care Boards that a region boundary cut in two are joined again.

The charities directory (vcse_data.json) is not merged: at about 100 MB for
England it is over GitHub Pages' file limit, and it stays in each region.
"""

from __future__ import annotations

import json
import math
import sys
from datetime import datetime, timezone
from pathlib import Path

from shapely.geometry import mapping, shape
from shapely.ops import unary_union

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from build_loader_map import ALPHABET, encode_varints, rdp  # noqa: E402

OUT = ROOT / "data" / "regions" / "england"

# Degrees. Wards, LSOAs and MSOAs at about 25 m; councils, drawn as outlines
# over everything else, at about 100 m.
TOL_SMALL = 0.00025
TOL_COUNCIL = 0.001

# An indicator is offered at a level only where it covers at least this share
# of England's areas at that level.
MIN_COVERAGE = 0.5

ICB_PALETTE = ["#8E44AD", "#C2701C", "#2E7D32", "#C0392B",
               "#1F6FB2", "#B8860B", "#00838F", "#AD1457"]


# ── reading and writing ─────────────────────────────────────────────────────
def read_js(path: Path, name: str):
    text = path.read_text(encoding="utf-8")
    marker = f"var {name} = "
    start = text.index(marker) + len(marker)
    end = max(text.rfind("}"), text.rfind("]")) + 1
    return json.loads(text[start:end])


def read_json(path: Path, default=None):
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def dump(value) -> str:
    return json.dumps(value, separators=(",", ":"), ensure_ascii=False)


def write_js(path: Path, name: str, value, note: str) -> None:
    path.write_text(f"// {note}\n// Generated by scripts/build_england.py. Do not hand edit.\n"
                    f"var {name} = {dump(value)};\n", encoding="utf-8")


def sources() -> list[tuple[str, Path]]:
    found = [("london", ROOT)]
    for scope in sorted((ROOT / "scopes").glob("*.json")):
        slug = scope.stem
        d = ROOT / "data" / "regions" / slug
        if slug not in ("london", "england") and (d / "map" / "wards.js").exists():
            found.append((slug, d))
    return found


def path_in(slug: str, src: Path, rel: str) -> Path:
    """A region's file by its region-relative name; London keeps map/ and
    meta/ under data/."""
    if slug == "london" and rel.split("/")[0] in ("map", "meta"):
        return src / "data" / rel
    return src / rel


# ── geometry ────────────────────────────────────────────────────────────────
def simplify(geom: dict, tol: float) -> dict | None:
    g = shape(geom)
    if not g.is_valid:
        g = g.buffer(0)
    s = g.simplify(tol, preserve_topology=True)
    if s.is_empty:
        return None
    m = mapping(s)
    # Five decimal places is about a metre: more is bytes nobody sees.
    def rnd(c):
        return [rnd(x) for x in c] if isinstance(c[0], (list, tuple)) else [round(c[0], 5), round(c[1], 5)]
    return {"type": m["type"], "coordinates": rnd(m["coordinates"])}


def merge_features(slug_srcs, rel: str, var: str | None, key: str, tol: float,
                   seen: set | None = None) -> list:
    seen = set() if seen is None else seen
    out = []
    for slug, src in slug_srcs:
        p = path_in(slug, src, rel)
        if not p.exists():
            continue
        gj = read_js(p, var) if var else read_json(p)
        for f in (gj or {}).get("features", []):
            props = f.get("properties") or {}
            code = props.get(key) or next((v for k, v in props.items()
                                           if k.upper().endswith("CD") and v), None)
            if not code or code in seen or not f.get("geometry"):
                continue
            geom = simplify(f["geometry"], tol)
            if not geom:
                continue
            seen.add(code)
            out.append({"type": "Feature", "properties": dict(props, _region=slug), "geometry": geom})
    return out


# ── indicator ranges ────────────────────────────────────────────────────────
def level_stats(records: list) -> dict:
    """{indicator: {n, d, p5, p95}} over one level's records."""
    vals: dict = {}
    for rec in records:
        for k, v in ((rec or {}).get("indicators") or rec or {}).items():
            if isinstance(v, (int, float)) and not isinstance(v, bool) and math.isfinite(v):
                vals.setdefault(k, []).append(float(v))
    out = {}
    for k, vs in vals.items():
        if len(vs) < 2 or len(vs) < MIN_COVERAGE * len(records):
            continue
        vs.sort()
        out[k] = {"n": len(vs), "d": len(set(vs)),
                  "p5": round(vs[int(len(vs) * 0.05)], 4),
                  "p95": round(vs[math.ceil(len(vs) * 0.95) - 1], 4)}
    return out


# ── loading screen ──────────────────────────────────────────────────────────
def loader_map(councils: list, deciles: dict) -> dict:
    rings = []
    for f in councils:
        g = f["geometry"]
        parts = [g["coordinates"]] if g["type"] == "Polygon" else g["coordinates"]
        rings.append((f["properties"].get("name"), max((p[0] for p in parts), key=len)))
    lats = [pt[1] for _, r in rings for pt in r]
    lons = [pt[0] for _, r in rings for pt in r]
    k = math.cos(math.radians((min(lats) + max(lats)) / 2))
    min_x, max_x, min_y, max_y = min(lons) * k, max(lons) * k, min(lats), max(lats)
    scale = 1000 / max(max_x - min_x, max_y - min_y)
    packed, dec = [], []
    for name, ring in rings:
        pts, last = [], None
        for pt in rdp(ring, 0.01):
            xy = (round((pt[0] * k - min_x) * scale), round((max_y - pt[1]) * scale))
            if xy != last:
                pts.append(xy)
                last = xy
        if len(pts) < 3:
            continue
        vals = [len(pts), pts[0][0], pts[0][1]]
        for i in range(1, len(pts)):
            vals += [pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]]
        packed.append(encode_varints(vals))
        dec.append(ALPHABET[deciles.get(name, 0)])
    return {"w": round((max_x - min_x) * scale), "h": round((max_y - min_y) * scale),
            "n": len(packed), "d": "".join(dec), "p": "".join(packed)}


def main() -> int:
    srcs = sources()
    published = [s for s, _ in srcs]
    missing = sorted(s.stem for s in (ROOT / "scopes").glob("*.json")
                     if s.stem not in set(published) | {"england"})
    print(f"regions: {', '.join(published)}; not published yet: {missing or 'none'}")
    (OUT / "map").mkdir(parents=True, exist_ok=True)
    (OUT / "meta").mkdir(parents=True, exist_ok=True)

    # Wards, with names made unique across England.
    wards = merge_features(srcs, "map/wards.js", "GJ", "WD24CD", TOL_SMALL)
    count: dict = {}
    for f in wards:
        count[f["properties"].get("WD24NM")] = count.get(f["properties"].get("WD24NM"), 0) + 1
    renamed = {}
    for f in wards:
        p = f["properties"]
        if count.get(p.get("WD24NM"), 0) > 1 and p.get("LAD") and "(" not in (p.get("WD24NM") or ""):
            p["WD24NM"] = f"{p['WD24NM']} ({p['LAD']})"
            renamed[p["WD24CD"]] = p["WD24NM"]
        p.pop("_region", None)
    print(f"  {len(wards):,} wards ({len(renamed):,} renamed to be unique)")
    write_js(OUT / "map/wards.js", "GJ", {"type": "FeatureCollection", "features": wards},
             "Ward boundaries for England, merged from the published regions.")

    ward_data = {"wards": {}, "metadata": {}}
    for slug, src in srcs:
        d = read_json(path_in(slug, src, "ward_data.json"), {})
        ward_data["wards"].update(d.get("wards", {}))
        if slug == "london":
            ward_data["metadata"] = d.get("metadata", {})
    for code, name in renamed.items():
        if code in ward_data["wards"]:
            ward_data["wards"][code]["name"] = name
    (OUT / "ward_data.json").write_text(dump(ward_data), encoding="utf-8")

    # Councils.
    councils = merge_features(srcs, "map/boroughs.js", "BOROUGH_GJ", "LAD25CD", TOL_COUNCIL)
    for f in councils:
        f["properties"]["region"] = f["properties"].pop("_region")
    write_js(OUT / "map/boroughs.js", "BOROUGH_GJ", {"type": "FeatureCollection", "features": councils},
             "Every local authority in England, from the published regions.")
    print(f"  {len(councils)} councils")

    # LSOAs (boundaries with IMD) and MSOAs.
    lsoas = merge_features(srcs, "map/lsoa_imd.js", "LSOA_IMD", "code", TOL_SMALL)
    deciles: dict = {}
    for f in lsoas:
        p = f["properties"]
        p.pop("_region", None)
        if p.get("ward_code") in renamed:
            p["ward"] = renamed[p["ward_code"]]
        if p.get("borough") and isinstance(p.get("imd_decile"), (int, float)):
            deciles.setdefault(p["borough"], []).append(p["imd_decile"])
    write_js(OUT / "map/lsoa_imd.js", "LSOA_IMD", {"type": "FeatureCollection", "features": lsoas},
             "LSOA boundaries for England with IMD decile and rank, and their ward.")
    msoas = merge_features(srcs, "map/msoa_boundaries.json", None, "code", TOL_SMALL)
    for f in msoas:
        f["properties"].pop("_region", None)
    (OUT / "map/msoa_boundaries.json").write_text(
        dump({"type": "FeatureCollection", "features": msoas}), encoding="utf-8")
    print(f"  {len(lsoas):,} LSOAs, {len(msoas):,} MSOAs")

    # Figures keyed by code: a straight merge.
    merged = {}
    for rel in ("lsoa_data.json", "msoa_data.json", "borough_data.json"):
        m: dict = {}
        for slug, src in srcs:
            m.update(read_json(path_in(slug, src, rel), {}) or {})
        merged[rel] = m
        (OUT / rel).write_text(dump(m), encoding="utf-8")

    # Points, de-duplicated where two regions both list a site near their edge.
    def points(rel: str, var: str | None):
        out, seen = [], set()
        for slug, src in srcs:
            p = path_in(slug, src, rel)
            if not p.exists():
                continue
            for r in (read_js(p, var) if var else read_json(p, [])) or []:
                k = (r.get("n") or r.get("name"), round(float(r.get("lat") or 0), 4),
                     round(float(r.get("lng") or r.get("lon") or 0), 4))
                if k not in seen:
                    seen.add(k)
                    out.append(r)
        return out
    write_js(OUT / "map/gp_practices.js", "GPS", points("map/gp_practices.js", "GPS"),
             "GP practices in England, from the published regions.")
    write_js(OUT / "map/hospitals.js", "HOSP", points("map/hospitals.js", "HOSP"),
             "Hospitals and clinics in England, from the published regions.")
    write_js(OUT / "map/custom.js", "PH_CUSTOM", [], "No custom indicators at England level.")
    for rel in ("pharmacies.json", "dental_practices.json"):
        (OUT / rel).write_text(dump(points(rel, None)), encoding="utf-8")

    # Indicator ranges across England, at each level.
    yr: dict = {}
    for slug, src in srcs:
        p = path_in(slug, src, "map/indicators.js")
        if p.exists():
            for k, v in (read_js(p, "PH_IND_STATS").get("stats") or {}).items():
                if v.get("yr") and k not in yr:
                    yr[k] = v["yr"]
    levels = {
        "ward": level_stats(list(ward_data["wards"].values())),
        "lsoa": level_stats(list(merged["lsoa_data.json"].values())),
        "msoa": level_stats(list(merged["msoa_data.json"].values())),
        "borough": level_stats(list(merged["borough_data.json"].values())),
    }
    stats: dict = {}
    for lv, per in levels.items():
        for k, s in per.items():
            stats.setdefault(k, {"lv": {}})["lv"][lv] = s
    for k in stats:
        if k in yr:
            stats[k]["yr"] = yr[k]
    write_js(OUT / "map/indicators.js", "PH_IND_STATS",
             {"generated": datetime.now(timezone.utc).isoformat(), "stats": stats},
             "Per-indicator facts measured across England.")
    print(f"  {len(stats)} indicators with England-wide coverage")

    # Integrated Care Boards, re-joined where a region boundary split one.
    parts: dict = {}
    lad_to = {}
    for slug, src in srcs:
        gj = read_json(path_in(slug, src, "map/icbs.json"))
        lk = read_json(path_in(slug, src, "map/icb_lookup.json"), {}) or {}
        lad_to.update(lk.get("lad_to_icb", {}))
        for f in (gj or {}).get("features", []):
            p = f["properties"]
            e = parts.setdefault(p["name"], {"label": p.get("label") or f"NHS {p['name']} ICB",
                                             "geoms": [], "boroughs": []})
            e["geoms"].append(shape(f["geometry"]).buffer(0))
            e["boroughs"] += p.get("boroughs", [])
    if parts:
        merged_geom = {n: unary_union(e["geoms"]) for n, e in parts.items()}
        touch = {i: {j for j in parts if j != i and merged_geom[i].buffer(1e-4).intersects(merged_geom[j])}
                 for i in parts}
        colour = {}
        for i in sorted(parts, key=lambda i: -len(touch[i])):
            used = {colour[j] for j in touch[i] if j in colour}
            colour[i] = next((c for c in ICB_PALETTE if c not in used), ICB_PALETTE[0])
        names = sorted(parts)
        feats = []
        for n in names:
            g = simplify(mapping(merged_geom[n]), TOL_COUNCIL)
            feats.append({"type": "Feature", "geometry": g, "properties": {
                "name": n, "label": parts[n]["label"], "boroughs": sorted(set(parts[n]["boroughs"])),
                "n_boroughs": len(set(parts[n]["boroughs"])), "colour": colour[n]}})
        (OUT / "map/icbs.json").write_text(dump({"type": "FeatureCollection", "features": feats}),
                                           encoding="utf-8")
        (OUT / "map/icb_lookup.json").write_text(json.dumps({
            "order": names, "colours": colour,
            "labels": {n: parts[n]["label"] for n in names},
            "counts": {n: len(set(parts[n]["boroughs"])) for n in names},
            "lad_to_icb": lad_to, "partial": []}, indent=1, ensure_ascii=False), encoding="utf-8")
        print(f"  {len(names)} ICBs")

    # Loading screen and manifest.
    dec = {k: max(1, min(10, round(sum(v) / len(v)))) for k, v in deciles.items()}
    (OUT / "map/loader.js").write_text(
        "// The loading screen's council map for England, made by scripts/build_england.py.\n"
        f"var REGION_LOADER_MAP = {dump(loader_map(councils, dec))};\n", encoding="utf-8")
    manifest = read_json(ROOT / "data/meta/manifest.json", {}) or {}
    manifest["england"] = {"regions": published, "not_yet_published": missing,
                           "wards": len(wards), "councils": len(councils)}
    (OUT / "meta/manifest.json").write_text(json.dumps(manifest, indent=1), encoding="utf-8")

    for p in sorted(OUT.rglob("*")):
        if p.is_file():
            print(f"    {p.relative_to(OUT)}  {p.stat().st_size / 1e6:6.1f} MB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
